const data = [
    {
        id:1,
        name: 'John',
        followStatus: false,
        time: 5,
        img :'../../../../src/assets/Banner/img1.jpg',
        text:"হ্যালো, গারো পাহাড় থেকে বলছি📍নালিতাবাড়ী,শেরপুর।",
    },
    {
        id:2,
        name: 'Dhairy Shah',
        followStatus: true,
        time: 2,
        img :'../../../../src/assets/Banner/img2.jpg',    text:"আমি কিছুদিন যাবত একটু ব্যস্ত থাকার কারনে Facebook group এবং Email চেক করতে পারিনি। এর ফলে আমি  Discord Channel এ যুক্ত হতে পারিনি। এখন আমি যুক্ত হতে পারছি না।",
    },
    {
        id:3,
        name: 'Abraham Khan',
        followStatus: true,
        time: 1,
        img :'../../../../src/assets/Banner/img3.jpg',    text:"Let's go...",
    },
    {
        id:4,
        name: 'Tasrif Khan',
        followStatus: false,
        time: 28,
        img :'../../../../src/assets/Banner/img4.jpg',    text:"Tips to Enhance Dark 🌑 UI Design by UI UX Jarar",
    },
    {
        id:5,
        name: 'Mehedi Hasan Rihat',
        followStatus: false,
        time: 7,
        img :'../../../../src/assets/Banner/img5.jpg',    text:"Allow The Switch...",
    },
    {
        id:6,
        name: 'Rohit Sharma',
        followStatus: true,
        time: 5,
        img :'../../../../src/assets/Banner/img6.jpg',    text:"ট্রেইল... ",
    },
    {
        id:7,
        name: 'Abir',
        followStatus: false,
        time: 9,
        img :'../../../../src/assets/Banner/img7.jpg',    text:"Learn how to be strong alone.",
    },    {
        id:8,
        name: 'John',
        followStatus: false,
        time: 5,
        img :'../../../../src/assets/Banner/img8.jpg',    text:"মুগ্ধ তোরণের সামনে দাড়িয়ে আছে স্নিগ্ধ মুগ্ধ আমাদের মাঝে বেঁচে থাকবে আজীবন",
    },
    {
        id:9,
        name: 'John',
        followStatus: false,
        time: 5,
        img :'../../../../src/assets/Banner/img1.jpg',
        text:"হ্যালো, গারো পাহাড় থেকে বলছি📍নালিতাবাড়ী,শেরপুর।",
    },
    {
        id:10,
        name: 'Dhairy Shah',
        followStatus: true,
        time: 2,
        img :'../../../../src/assets/Banner/img2.jpg',    text:"আমি কিছুদিন যাবত একটু ব্যস্ত থাকার কারনে Facebook group এবং Email চেক করতে পারিনি। এর ফলে আমি  Discord Channel এ যুক্ত হতে পারিনি। এখন আমি যুক্ত হতে পারছি না।",
    },
    {
        id:11,
        name: 'Abraham Khan',
        followStatus: true,
        time: 1,
        img :'../../../../src/assets/Banner/img3.jpg',    text:"Let's go...",
    },
    {
        id:12,
        name: 'Tasrif Khan',
        followStatus: false,
        time: 28,
        img :'../../../../src/assets/Banner/img4.jpg',    text:"Tips to Enhance Dark 🌑 UI Design by UI UX Jarar",
    },
    {
        id:13,
        name: 'Mehedi Hasan Rihat',
        followStatus: false,
        time: 7,
        img :'../../../../src/assets/Banner/img5.jpg',    text:"Allow The Switch...",
    },
    {
        id:14,
        name: 'Rohit Sharma',
        followStatus: true,
        time: 5,
        img :'../../../../src/assets/Banner/img6.jpg',    text:"ট্রেইল... ",
    },
    {
        id:15,
        name: 'Abir',
        followStatus: false,
        time: 9,
        img :'../../../../src/assets/Banner/img7.jpg',    text:"Learn how to be strong alone.",
    },    {
        id:16,
        name: 'John',
        followStatus: false,
        time: 5,
        img :'../../../../src/assets/Banner/img8.jpg',    text:"মুগ্ধ তোরণের সামনে দাড়িয়ে আছে স্নিগ্ধ মুগ্ধ আমাদের মাঝে বেঁচে থাকবে আজীবন",
    },
    
    {
        id:17,
        name: 'John',
        followStatus: false,
        time: 5,
        img :'../../../../src/assets/Banner/img1.jpg',
        text:"হ্যালো, গারো পাহাড় থেকে বলছি📍নালিতাবাড়ী,শেরপুর।",
    },
    {
        id:18,
        name: 'Dhairy Shah',
        followStatus: true,
        time: 2,
        img :'../../../../src/assets/Banner/img2.jpg',    text:"আমি কিছুদিন যাবত একটু ব্যস্ত থাকার কারনে Facebook group এবং Email চেক করতে পারিনি। এর ফলে আমি  Discord Channel এ যুক্ত হতে পারিনি। এখন আমি যুক্ত হতে পারছি না।",
    },
    {
        id:19,
        name: 'Abraham Khan',
        followStatus: true,
        time: 1,
        img :'../../../../src/assets/Banner/img3.jpg',    text:"Let's go...",
    },
    {
        id:20,
        name: 'Tasrif Khan',
        followStatus: false,
        time: 28,
        img :'../../../../src/assets/Banner/img4.jpg',    text:"Tips to Enhance Dark 🌑 UI Design by UI UX Jarar",
    },
    {
        id:21,
        name: 'Mehedi Hasan Rihat',
        followStatus: false,
        time: 7,
        img :'../../../../src/assets/Banner/img5.jpg',    text:"Allow The Switch...",
    },
    {
        id:22,
        name: 'Rohit Sharma',
        followStatus: true,
        time: 5,
        img :'../../../../src/assets/Banner/img6.jpg',    text:"ট্রেইল... ",
    },
    
   
]

export default data;